### PR TITLE
Ecis to ece transfer

### PR DESCRIPTION
**Pull request by kmagida110**
Here is the code that I used to create the data for loading to ECE Reporter from ECIS. If you could take a look at the logic below (it is in the code too) that would be great. The biggest issue is that there are 12 sites that have codes that aren't in the file we currently have. I mapped them to the best guess of an org but we'll need to decided whether to make new sites for them or map them to existing sites with the old ID number.  There are also some questionable mappings between exit reasons, if you could validate my assumptions there that would be great.

Column notes:
`
### ECE Columns tracking

- First name - Copy
- (OPTIONAL) Middle name - Copy
- Last name - Copy
- (OPTIONAL) Suffix - Copy
- (OPTIONAL) SASID / unique identifier - Copy
- Date of birth - Done
- (OPTIONAL) Birth certificate type - Not included
- (OPTIONAL) Birth certificate ID # - None in file
- (OPTIONAL) Town of birth - None in file
- (OPTIONAL) State of birth - None in file
- Race: American Indian or Alaska Native - Copy
- Race: Asian - Copy
- Race: Black or African American - Copy
- Race: Native Hawaiian or Pacific Islander - Copy
- Race: white - Copy
- Race not disclosed - Calculated
- Hispanic or Latinx ethnicity - Calculated 
- Gender - Calculated
- (OPTIONAL) Dual language learner - Not in file
- (OPTIONAL) Receiving disability and/or special education services - Calculated from has IEP
- Street address - Calculated
- Town - Copy
- State - Copy
- Zipcode - Copy (loaded as string)
- (OPTIONAL) Lives with foster family - Calculated
- (OPTIONAL) Experiencing homelessness or housing insecurity - Not in file
- Household size - Filled na number with ''
- Annual household income - Filled na number with '' 
- Determination date - Filled na number with ''  
- Provider - Uses our ID'd provider for sites in our system
- Site - Name of the site in our system, joined off facility ID
- (OPTIONAL) Care model - Not in file, set as 'Unknown'
- Age group - Calculated from funding and space type
- Enrollment start date - Converted to String (potentially better data in ECIS)
- Enrollment end date - Converted to String
- Enrollment exit reason - Replacement 
- Funding type - Mapping, missing (Head Start/Early Head Start, Private Pay and PDG-Federal were removed)
- Space type - Calculated from funding and space type
- First funding period - Converted to str
- Last funding period - Converted to str

Replacement mapping
EXIT_REASONS = {'Aged Out':'Aged out',
                'Child Stopped Attending':'Stopped attending',
                'Chose to Attend A Different Program':'Chose to attend a different program',
                'Moved to Another Town':'Moved within Connecticut',
                'Moved to Another State':'Moved to another state',
                'Child Was Asked To Leave':'Child was asked to leave',
                'Other':'Unknown',
                'Parent Withdrew Child':'Stopped attending',
                'Unknown':'Unknown'}

site_to_org_mapping = {'Lulac': 'City of New Haven',
                       'Saint Aedan Elementary School':'Catholic Academy of New Haven-St. Aedan Pre School',
                       'Hospital for Special Care':'Hospital for Special Care',
                       'Bright and Early Children Learning Center':"Bright and Early Children's Learning Centers I",
                       'Gallup Hill School':'Gallup Hill School',
                       'Early Childhood - CT Office of':'Early Childhood - CT Office of',
                       'Alice Peck Learning Center':'Hamden BOE',
                       'TVCCA Groton ECE':'Thames Valley Council for Comm. Action TVCCA)',
                       'Hockanum Pre-K':'East Hartford BOE',
                       'WCSU Child Care Center':'WCSU Child Care Center',
                       'Colchester Early Childhood':'Colchester BOE',
                       'Precious Memories lll':'Precious Memories Early Childhood Learning Center'                       
                      }
`

### CODE REVIEW

**Comment by RyanHansz** [comment]
@kmagida110 for income determinations, do we know if "Filled na number with ''" means there was no income entered by the user or that income info isn't included in the data export?

**Comment by kmagida110** [comment]
@RyanHansz I can't tell for sure but I would guess that it is no income entered by user because I don't know of any reason it wouldn't be included in the export. Some of the rows with no income have number of people in the family or income determination date (which is strange) or first name so I would doubt that there is a systematic issue is exporting

**Comment by RyanHansz** [comment]
> @RyanHansz I can't tell for sure but I would guess that it is no income entered by user because I don't know of any reason it wouldn't be included in the export. Some of the rows with no income have number of people in the family or income determination date (which is strange) or first name so I would doubt that there is a systematic issue is exporting

I would lean towards marking those as "income not disclosed" rather than empty. If income is empty it will be flagged as an error.

**Comment by jlhogan** [comment]
@RyanHansz sounds good! at a certain point, income disclosure will become required once again and any data that was erroneously marked as "not disclosed" will get updated

**Comment by kmagida110** [comment]
@RyanHansz @jlhogan There doesn't seem to be an income not disclosed column to use here. Should I just use the text 'income not disclosed", will that be rejected since it is not numeric?

**Comment by jlhogan** [comment]
there is an income not disclosed column; the template has been updated and the updates were just deployed to prod

**Comment by kmagida110** [comment]
@jlhogan This should be updated, the file it outputs matches the template. I had issue uploading any file, including the provided template, into my local instance of ECE Reporter so couldn't verify that but this should be good. When this approved and you are ready to load let me know and we can coordinate the upload/secure transfer. Julie said she is going to try to get an attempt to fill the blank names today.

**Comment by kmagida110** [comment]
I also added logic only including rows that have updated since 7/1/2020, it shrunk the file from ~8000 rows to ~5000 rows

**Comment by jlhogan** [comment]
i thought we won't be ready to load until we have the names from julie? also, you wont be able to load the data if the orgs and sites dont exist in your local DB, so that's likely why the upload fails.

**Review by jlhogan — APPROVED** [review]

**Comment by jlhogan** [comment]
Also, once we have the comprehensive list of orgs/providers that we have data for, I think we should ask those various providers if they want their ECIS data loaded. Will want to ensure we dont add data for users who have already put data in the tool. Additionally, we will only want to upload data for the orgs/sites that exist in the system right now. Also we will need to make sure the org/Site names match those in ECE Reporter DB, which is a list you can just pull from the DB or i can provide to you if you're not hooked up

**Comment by kmagida110** [comment]
Yeah, we have to wait for the names, I just wanted to have a note in the ticket that there is still some work to be done to transfer. That makes sense on the site names but I wasn't even able to upload the template, regardless, we should be set. 

I'll throw together a ticket for the double checking of existing data.

**Comment by jlhogan** [comment]
>makes sense on the site names but I wasn't even able to upload the template

what does that mean? like empty template? you should get an error message that your file was empty if that's the case

**Comment by kmagida110** [comment]
The dummy data template

**Comment by kmagida110** [comment]
`TypeError: controller.getCount is not a function
Upload/</<
src/containers/Upload/Upload.tsx:36

  33 |   apiGet('children?count=true', accessToken)
  34 |     .then((res) => setUserRosterCount(res.count))
  35 |     .catch((err) => {
> 36 |       throw new Error(err);
     | ^  37 |     });
  38 | }, [accessToken]);
  39 | 

This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.`

When I commented out that code, the app itself said the file wasn't formatted correctly.

**Comment by jlhogan** [comment]
ah so we moved some stuff around, and the dev build doesn't clean out removed files from `dist` (the build app)
If you remove that directory, and then rebuild the application, should be all good
```
$ sudo rm -rf dist
$ docker-compose server yarn build
```

**Comment by kmagida110** [comment]
Yup, I just figured since it had been a while since I started it should be fresh, that isn't how computers work.....

**Pull request merged**
